### ISSUE TITLE
Segmentation fault for a given dataset.

### ISSUE THREAD

**Issue by alecuba16** [mbq/praznik#2]
Hello Miron,

I'm currently testing a subset of my dataset with your new CMIM implementation. The problem is that I'm getting segmentation fault on my Gentoo Linux computer:

>  kernel: [109940.927164] rsession[26215]: segfault at 8053a32d8 ip 00007f9aa804baaf sp 00007ffcabbe2880 error 4 in praznik.so[7f9aa8049000+9000]

I don't know where is the problem, if it is a free memory problem (I got about 23GB free), or something due the type of data.

[Here is the subset of the dataset that doesn't work](https://drive.google.com/open?id=1tTxZ-edg3xkGTWjtusBvobnhwc2Ghr2V)

The feature matrix is X (rows = observations, columns=variables), it is already centered and scaled:
*X-mean/sdv*  ,  and I did this checks:

> \>class(X)
>[1] "data.frame"
> \>any(is.na(X))
>[1] FALSE
> \>any(is.null(X))
>[1] FALSE
> \>unique(apply(X,2,class))
>[1] "numeric"

The target/classes array is y and the checks:

> \>any(is.na(y))
>[1] FALSE
> \>any(is.null(y))
>[1] FALSE
> \>class(y)
>[1] "factor"
> \>levels(y)
>[1] "0" "1"

I would appreciate any advice if I'm doing it wrong or if it is just a memory limit problem.
Thanks.

**Comment by alecuba16** [comment]
I made a algorithm that was appending feature by feature and I have found that the feature nº109 ('nrecords') is the responsibile of segmentation fault, I did a *unique()* check and the lenght is 1 , which means that is a constant.

So the praznik code is not prepared to deal with constants? I know that is my fault because I didn't checked it before, but maybe a warning or skip message will be helpful?

**Comment by mbq** [comment]
Yup, that's a bug, working on it. As a workaround, you can manually discretize features, factors with one level are OK.

**Comment by mbq** [comment]
So, the devel branch has this fixed, should appear on CRAN soon with a bunch of other changes which allow for parallel processing.

**Comment by alecuba16** [comment]
Nice to see openMP implementation on the several for loops.
